config/routes.rb
Swaggard::Engine.routes.draw do
   get '/(.:format)', to: 'swagger#index', as: :doc
end

app/controllers/swaggard/application_controller.rb
module Swaggard
  class ApplicationController < ActionController::Base
  end
end

app/controllers/swaggard/swagger_controller.rb
module Swaggard
  class SwaggerController < ApplicationController

    before_action :authorize

    def index
      respond_to do |format|
        format.html do
          @authentication_type = Swaggard.configuration.authentication_type
          @authentication_key = Swaggard.configuration.authentication_key
          @authentication_value = Swaggard.configuration.authentication_value.respond_to?(:call) ?
                                    Swaggard.configuration.authentication_value.call :
                                    Swaggard.configuration.authentication_value

          render :index, layout: false
        end

        format.json do
          render json: get_swaggard_doc_json, :adapter => :attributes
        end
      end
    end

    protected

    def authorize
      unless Swaggard.configuration.access_username.blank?
        authenticate_or_request_with_http_basic do |username, password|
          username == Swaggard.configuration.access_username && password == Swaggard.configuration.access_password
        end
      end
    end

    def get_swaggard_doc_json
      if Swaggard.configuration.use_cache
        doc_json = Rails.cache.fetch('swaggard_doc_json')
        if doc_json.blank?
          doc_json = Swaggard.get_doc(request.host_with_port).as_json
          Rails.cache.write('swaggard_doc_json', doc_json)
        end
        doc_json
      else
        Swaggard.get_doc(request.host_with_port).as_json
      end
    end

  end
end

app/views/swaggard/swagger/doc.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swagger UI</title>

  <%= stylesheet_link_tag    'swaggard/application', media: 'all' %>
  <%= javascript_include_tag 'swaggard/application' %>

  <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = location.protocol + "//" + location.host + "/swagger/api";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        sorter : "alpha"
      });

      function addApiKeyAuthorization() {
        var key = $('#input_apiKey')[0].value;
        log("key: " + key);
        if(key && key.trim() != "") {
          log("added key " + key);
          window.authorizations.add('key', new ApiKeyAuthorization("<%= @authentication_key %>",
                                           key,
                                           "<%= @authentication_type %>"));
        }
      }

      var $apiKeyInput = $('#input_apiKey');

      $apiKeyInput.change(function() {
        addApiKeyAuthorization();
      });

      var apiKey = "<%= @authentication_value %>";
      $apiKeyInput.val(apiKey);
      addApiKeyAuthorization();

      window.swaggerUi.load();
    });
  </script>
</head>

<body class="swagger-section">
<div id='header'>
  <div class="swagger-ui-wrap">
    <a id="logo" href="http://swagger.io">swagger</a>
    <form id='api_selector'>
      <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
      <div class='input'><input placeholder="<%= @authentication_key %>" id="input_apiKey" name="apiKey" type="text"/></div>
      <div class='input'><a id="explore" href="#">Explore</a></div>
    </form>
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap">&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</body>
</html>

app/views/swaggard/swagger/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger UI</title>

    <%= favicon_link_tag 'swaggard/favicon-32x32.png', sizes: '32x32' %>
    <%= favicon_link_tag 'swaggard/favicon-16x16.png', sizes: '16x16' %>

    <%= stylesheet_link_tag 'swaggard/application', media: :screen %>
    <%= stylesheet_link_tag 'swaggard/application_print', media: :print %>

    <%= javascript_include_tag 'swaggard/application' %>
    <%= javascript_include_tag "swaggard/lang/#{Swaggard.configuration.language}" %>

    <%= javascript_tag do %>
        window.default_content_type = '<%= Swaggard.configuration.default_content_type %>';
    <% end %>

  </head>

  <body class='swagger-section' data-doc-path='<%= doc_path(format: :json)%>'>
    <div id='header'>
      <div class='swagger-ui-wrap'>
        <a id='logo' href='http://swagger.io'>
          <%= image_tag 'swaggard/logo_small.png', class: 'logo__img', alt: 'swagger', height: 30, width: 30 %>
          <span class='logo__title'>swagger</span>
        </a>
        <%= form_tag '', id: :api_selector do %>

          <div>
            <div class='input'><input placeholder='http://example.com/api_docs/swagger.json' id='input_baseUrl' name='baseUrl' type='text'/></div>

            <div class='input'>
              <input class='additional_parameter' data-parameter-key='<%= @authentication_key %>'
                                                  data-parameter-type='<%= @authentication_type %>'
                                                  placeholder='<%= @authentication_key %>'
                                                  type='text'
                                                  value='<%= @authentication_value %>'/>
              </div>

            <div class='input'><a id='explore' class='header__btn' href='#' data-sw-translate>Explore</a></div>
          </div>
          <% Swaggard.configuration.additional_parameters.each do |additional_parameter|%>
            <div class='input'>
              <input class='additional_parameter' data-parameter-key='<%= additional_parameter[:key] %>'
                                                  data-parameter-type='<%= additional_parameter[:type] %>'
                                                  placeholder='<%= additional_parameter[:key] %>'
                                                  type='text'
                                                  value='<%= additional_parameter[:value] %>'/>
              </div>
          <% end %>
          <div id='auth_container'></div>
        <% end %>
        <br>
        <br>
      </div>
    </div>

    <div id='message-bar' class='swagger-ui-wrap' data-sw-translate>&nbsp;</div>
    <div id='swagger-ui-container' class='swagger-ui-wrap'></div>
  </body>
</html>